# Generated by Django 3.2.8 on 2024-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_history_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ultra_processed',
            field=models.FloatField(default=0),
        ),
    ]
