# Generated by Django 3.2.8 on 2024-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_ultra_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bale_quantity_static',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_static',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit_static',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
