# Generated by Django 3.2.8 on 2024-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20240506_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_3',
            field=models.FloatField(default=0),
        ),
    ]
