# Generated by Django 3.2.8 on 2024-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_alter_transfer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_transfer',
            name='ultra_processed',
            field=models.FloatField(default=0),
        ),
    ]
