# Generated by Django 3.2.8 on 2024-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payroll_was_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='cune',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
