# Generated by Django 3.2.8 on 2024-03-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0112_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='ZIVARDJjiu', max_length=10),
        ),
    ]
