# Generated by Django 3.2.8 on 2024-04-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0115_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='jjMs4epSRD', max_length=10),
        ),
    ]
