# Generated by Django 3.2.8 on 2024-05-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0121_auto_20240508_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='P2x9jMPYjO', max_length=10),
        ),
    ]
