# Generated by Django 3.2.8 on 2024-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0123_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='a1UdBjFJCR', max_length=10),
        ),
    ]
