# Generated by Django 3.2.8 on 2024-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0127_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='ItDoYy6LBn', max_length=10),
        ),
    ]
