# Generated by Django 3.2.8 on 2024-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0112_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='NyOnlUV5Bo8o57GwhDfA', max_length=20, unique=True),
        ),
    ]
