# Generated by Django 3.2.8 on 2024-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0118_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='rlD8z8LveVsPPxKtx5gv', max_length=20, unique=True),
        ),
    ]
