# Generated by Django 3.2.8 on 2024-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0119_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='tMlVb0aqTFGcxSdWP0fN', max_length=20, unique=True),
        ),
    ]
