# Generated by Django 3.2.8 on 2024-03-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_auto_20240304_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='QRStr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='urlinvoicepdf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='urlinvoicexml',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
