# Generated by Django 3.2.8 on 2024-03-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_auto_20240316_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='QRStr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='urlinvoicepdf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='urlinvoicexml',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
