# Generated by Django 3.2.8 on 2024-04-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0112_alter_employee_psswd'),
        ('invoice', '0021_invoice_cude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('destination', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('on_rute', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='user.employee')),
                ('employee_who_receives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_who_receives', to='user.employee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
