# Generated by Django 3.2.8 on 2024-05-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_shipping_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_invoice',
            name='ultra_processed',
            field=models.FloatField(default=0),
        ),
    ]
