# Generated by Django 3.2.8 on 2024-05-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_details_invoice_ultra_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='consumption_tax',
            field=models.FloatField(default=0),
        ),
    ]
