# Generated by Django 3.2.8 on 2024-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_invoice_consumption_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
