# Generated by Django 3.2.8 on 2024-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_invoice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='consumption_tax',
            field=models.BooleanField(default=False),
        ),
    ]
