# Generated by Django 3.2.8 on 2024-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_pass_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ultra_processed',
            field=models.FloatField(default=0),
        ),
    ]
